# Pull image with python 3.9 and nodejs 16
FROM nikolaik/python-nodejs:python3.9-nodejs16

RUN npm install -g nodemon

WORKDIR /node-red-contrib-quantum

COPY . .

EXPOSE 1880

ENTRYPOINT [ "nodemon", "--exec", "npx", "node-red", "flows_quantum.json" ]