# Pull image with python 3.9 and nodejs 16
FROM nikolaik/python-nodejs:python3.9-nodejs16

RUN npm install -g nodemon

WORKDIR /node-red-contrib-quantum

COPY package*.json .

COPY bin ./bin

RUN npm install && \
    npm run setup

EXPOSE 1880
