# Pull image with python 3.9 and nodejs 16
FROM nikolaik/python-nodejs:python3.9-nodejs16
# Install nodemon and node-red globally
RUN npm install -g nodemon node-red
# Setup working directory
WORKDIR /node-red-contrib-quantum

USER root

EXPOSE 1880

ENTRYPOINT [ "nodemon", "--exec", "node-red", "flows_quantum.json" ]